<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=isset($title) ? $title : 'Error !'?></title>
<link rel="stylesheet" href="<?=url('css/error.css')?>" type="text/css" />
</head>

<body>

<?=partial_view('error/__' . (isset($code) ? $code : 404))?>

<? if (ENVIRONMENT !== PRODUCTION): ?>
    <?=partial_view('runtime/trace')?>
    <?=partial_view('runtime/profiler')?>
<? endif; ?>

</body>
</html>
